application: 5defence
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on

error_handlers:
  - file: html/error.html

  - error_code: over_quota
    file: html/quota.html

handlers:

- url: /scripts
  static_dir: scripts

- url: /styles
  static_dir: styles

- url: /images
  static_dir: images
  expiration: "1d"

- url: /.*
  script: main.py

